### PR TITLE
Support more versions of `fs`, other bugfixes

### PR DESCRIPTION
**Pull request by dargueta**
## Bugfixes

* Fixed handling of directories when opening a nonexistent file in exclusive mode. Before, if the file didn't exist and was opened in exclusive mode, it would throw the wrong exception. This was what was breaking compatibility with v2.1.1+.
* Fixed race condition in `openbin()` where the file lock was being released too early. We need to create the file object first before releasing the lock, since the file object needs it in the constructor.
* Added missing `pytest-rerunfailures` to test requirements. This required downgrading `pytest`.
* Fixed .gitignore to for ignoring *directories* named `.idea` and `.eggs` not *files* with those names

## Other changes

* Removed `.idea` directory since it was never supposed to be added (judging from the gitignore)
* Narrowed exception catching in `exists()` to only `ResourceNotFound`, not any exception. This avoids hiding Dropbox API errors or other programming mistakes that would otherwise go unnoticed.
* Deleted `requirements.txt` as it was outdated and no longer used.
* Bumped minimum `fs` version from 2.0.7 to 2.0.26 for some bugfixes around atomic file creation.

### CODE REVIEW

**Comment by dargueta** [comment]
@zopyx could you take a look at this please?

**Comment by zopyx** [comment]
I will check during the next days. Very busy ATM.

**Comment by dargueta** [comment]
Okay, thanks!

**Comment by zopyx** [comment]
https://pypi.org/project/fs.dropboxfs/0.2.2/

**Comment by zopyx** [comment]
need to check why there is no README appearing on PyPI.

**Comment by dargueta** [comment]
Found the problem -- it's a missing comma in `setup.cfg`. I'll fix it right now.

**Comment by dargueta** [comment]
Done: https://github.com/PyFilesystem/fs.dropboxfs/pull/5
Really sorry about this. Do you have an account on the test PyPI site where you can check to make sure this works before deploying to the real PyPI?

**Pull request merged**
