### PR TITLE
Fix installation issues

### LINKED ISSUE #1: 0.2.0 pypi release doesn't install
I get the following installing on python 3.7 (windows and macos)

Collecting fs.dropboxfs
  Downloading https://files.pythonhosted.org/packages/45/77/4ccf2f3d220791bc41beb19ad07b02723a279d376cdf437822a19e5382b
/fs.dropboxfs-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rkhwaja\AppData\Local\Temp\pip-install-tctd2y6r\fs.dropboxfs\setup.py", line 21, in <module>
        with io.open('HISTORY.rst', 'r', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\rkhwaja\AppData\Local\Temp\pip-install-tctd2y6r
fs.dropboxfs\

### PR DESCRIPTION
**Pull request by dargueta**
Fixes #1 and changes a few other things

## Installation

* Declare universal wheel support
* Declare Python 3.8 support -- we've been testing it but don't have it in the classifiers
* Add `python_requires` to make pip block installation on unsupported Python versions
* Remove outdated installation requirement -- tests now use pytest, but package still requires nose for installation.

## CI

* Test Python 3.5 -- we say we support it but don't test it
* Test PyPy and PyPy 3.5 -- we say we support PyPy but don't test it
* Upgrade Linux dist to Xenial so we get native 3.6 and 3.7 support

## General cleanup

* Move most configuration over to setup.cfg. More info on why/how [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files).
* Remove dynamic creation of `long_description` that accesses the filesystem. Local I/O is a frequent source of trouble (see #1) and tends to break tools like `tox` <sup>\[citation needed\]</sup>. Using multiple files in the setup.cfg file has been supported since 2017.

### CODE REVIEW

**Comment by dargueta** [comment]
I can't replicate the failure locally for some reason.

**Comment by rkhwaja** [comment]
Maybe it's failing because the fs version changed so much. You could just fix the setup and leave the fs restriction to see if that's the problem...

**Comment by dargueta** [comment]
That's what I thought so I reverted it, and now I have the opposite problem -- most tests won't pass locally. I think it might be because this is hitting an actual DropBox account, so presumably failures will leave stray files and folders behind.

We should probably be using [vcrpy](https://pypi.org/project/vcrpy/) for this instead of using a live shared account.

**Update:** I just reran the tests locally after changing nothing and they *all* passed. 😕

**Comment by dargueta** [comment]
Okay so this is now failing even with `fs` back to the original version limitation. I'm suspecting it might actually be the dropbox API client itself?

**Comment by dargueta** [comment]
Fixed it! We can work on loosening the `fs` requirement next.

**Comment by dargueta** [comment]
@rkhwaja FYI

**Comment by rkhwaja** [comment]
@zopyx Can you merge this and make a new release?

**Comment by dargueta** [comment]
\*bump\*

Sorry to be annoying, but I'm gonna need this for a project at work soon. Release please?

**Comment by zopyx** [comment]
https://pypi.org/project/fs.dropboxfs/0.2.1/

**Comment by dargueta** [comment]
Thank you!

**Pull request merged**
